### ISSUE TITLE
Hoc should not show console.error if cannot load image

### ISSUE THREAD

**Issue by Knight704** [billmalarky/react-native-image-cache-hoc#10]
it should just stay with placeholder, not crash whole app

**Comment by billmalarky** [comment]
The app does not crash on error in production. The redbox error created by console.error() that you are seeing will only pop up in a development environment - this is so you will catch the bug. In production the error is silently ignored, and the outcome is the placeholder component will remain.

https://facebook.github.io/react-native/docs/debugging.html#in-app-errors-and-warnings

**Comment by Knight704** [comment]
@billmalarky, correct me if I wrong, but image loading error is absolutely valid flow that may happen. And even in development build there should not be red-box (maximum warning in my opinion), and this should not bother development process

**Comment by billmalarky** [comment]
Sure, I'll take a closer look and get back to you again.

**Comment by billmalarky** [comment]
Switched console.error() with console.warn() to gracefully handle image serving error debugging.

https://github.com/billmalarky/react-native-image-cache-hoc/commit/5d5d46173dde788718558ff6f5ee53dbfa1cbc0e
