### ISSUE TITLE
How to set expiration time for the cache to be deleted ?

### ISSUE THREAD

**Issue by Nitroman605** [billmalarky/react-native-image-cache-hoc#11]
Hi .

One of key aspects of cache images is the expiration date , which you can set to something like 7 days until the image is deleted . 

How I can do this with this lib ? 

Thanks in advance .

**Comment by billmalarky** [comment]
Currently the automatic cache invalidation logic purges files in first in
first out order when the cache max size is hit. So the cache will continue
to grow until the size limit of the entire cache is reached, at which point
the oldest files will be purged until the total cache size has shrunk below
the size limit again. You can increase this cache size limit via the
options setting:

https://github.com/billmalarky/react-native-image-cache-hoc/blob/master/README.md#options

Look for cachePruneTriggerLimit.

Cache size was chosen to be the limiting factor over expiration time as
that is a more standard constraint for mobile caches.

**Comment by billmalarky** [comment]
Since this isn't a bug, I'm going to go ahead and close this issue.

If your use case requires cache invalidation via time expiration, feel free to create a PR adding the functionality. I do ask that you please run  `npm run lint` and `npm test` prior to submitting a PR.
