### ISSUE TITLE
The local file is actually not used. Should set source.uri instead on of uri

### ISSUE THREAD

**Issue by ben5276** [billmalarky/react-native-image-cache-hoc#13]
Line 189 in imageCacheHoc.js
Should change into 

    let props = Object.assign({}, filteredProps, { source: { uri: this.state.localFilePath }});

Instead of  

    let props = Object.assign({}, filteredProps, { uri: this.state.localFilePath });

Currently no local file is actually used

**Comment by billmalarky** [comment]
Well this is embarrassing...

I'll patch it first thing tomorrow morning.

Great catch Ben.

**Comment by ben5276** [comment]
For Android, the local file path needs a prefix as well:
'file://'

**Comment by billmalarky** [comment]
This has been resolved. Thank you so much for catching this Ben!

https://github.com/billmalarky/react-native-image-cache-hoc/pull/14
