### ISSUE TITLE
removing dep on react-native-fetch-blob?

### ISSUE THREAD

**Issue by xaphod** [billmalarky/react-native-image-cache-hoc#18]
react-native-fetch-blob has no maintainer, and a ton of issues.
On a fresh project with React Native 0.54 I couldn't get RNFB working after following manual linking instructions etc.
Are you using a lot of complicated functionality of RNFB or would it be possible to use just boring old fetches?

**Comment by billmalarky** [comment]
The requirement for the RNFB dependency, or whatever replaces it, it the ability to download files to local disk (vanilla fetch() is not capable of this) and also some general file system functionality.

You can look for yourself at how RNFB is used by react-native-image-cache-hoc by searching for RNfetchblob in the [FileSystem class](https://github.com/billmalarky/react-native-image-cache-hoc/blob/master/lib/FileSystem.js).

I'm open to suggestions, but at the time of initial development there was not a good alternative.

**Comment by xcarpentier** [comment]
Why not an expo version using expo document api?

**Comment by billmalarky** [comment]
Can you link me to the expo document API and explain how it can be used to download files and access the file system?

**Comment by xcarpentier** [comment]
@billmalarky https://docs.expo.io/versions/latest/sdk/filesystem.html#content

**Comment by csotiriou** [comment]
if you check here https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#055 you will see that react native 0.54 adds local file fetch and blob fetch, so RNFB dependency may not be required

**Comment by billmalarky** [comment]
This is excellent. While I've got you, do you know of a good file system
library alternative?

**Comment by gtebbutt** [comment]
There's also a maintained fork of `react-native-fetch-blob` released under `rn-fetch-blob`: https://github.com/joltup/rn-fetch-blob#readme

**Comment by billmalarky** [comment]
Thanks for the heads up!

**Comment by adamivancza** [comment]
this would be great as it's causing a yellowbox warning on RN 0.56 now:
`Module RNFetchBlob requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

**Comment by billmalarky** [comment]
Thank you. Hoping to get some RN work in the near future.

**Comment by adamivancza** [comment]
If you don’t have time right now I can try to update to ‘rn-fetch-blob’ over the weekend. Hopefully this will only be a package.json update :)

**Comment by billmalarky** [comment]
I'm also going to try to get work in on my packages this weekend. Been slammed with my day job lately xD

**Comment by adamivancza** [comment]
Created a PR for this @billmalarky : https://github.com/billmalarky/react-native-image-cache-hoc/pull/30

**Comment by adamivancza** [comment]
you can close this issue now @billmalarky

**Comment by billmalarky** [comment]
Thanks again!

**Comment by mtimofiiv** [comment]
Still having the issue under Expo where installing version `2.0.0` will complain about RNFetchBlob:

<img width="372" alt="Screenshot 2019-08-24 at 11 53 38" src="https://user-images.githubusercontent.com/428948/63632285-da6bb880-c665-11e9-9a0b-bb558531f603.png">

A bit confusing as well cause [native.directory](https://www.native.directory) lists it as being compatible with Expo.
