### ISSUE TITLE
HTTP Source images not supported

### ISSUE THREAD

**Issue by shubhi15** [billmalarky/react-native-image-cache-hoc#19]
Hello 

I an getting following error upon initialization of CacheableImage 

i.e  Invalid source prop. <CacheableImage> props.source.uri should be a web accessible url with a valid protocol and host. NOTE: Default valid protocol is https, default valid hosts are *.

Could you tell me if current library supports http protocol links.

**Comment by billmalarky** [comment]
Http is not turned on by default, it must be whitelisted in the setup options:

https://github.com/billmalarky/react-native-image-cache-hoc#options

```
const CacheableImage = imageCacheHoc(Image, {
  
  // Allow http urls. 
  // Defaults to https only.
  validProtocols: ['http', 'https']

});
```
