### ISSUE TITLE
app showing error while http url images in ios and android platform 

### ISSUE THREAD

**Issue by pravesh19** [billmalarky/react-native-image-cache-hoc#23]
I implemented react-native-image-cache-hoc. When I run code HTTP URL images are not showing even I modified my info.plist file with arbitrary loads true.
this error I am getting always -
Error with task : Error: Invalid source prop. <CacheableImage> props.source.uri should be a web-accessible URL with a valid protocol and host. NOTE: Default valid protocol is https, default valid hosts are *.

I used also this -
export const CacheableImage = imageCacheHoc(Image, {
  validProtocols: ['http','https']
});

**Comment by billmalarky** [comment]
You have to enable http in the options.

See this closed issue:
https://github.com/billmalarky/react-native-image-cache-hoc/issues/19

**Comment by pravesh19** [comment]
I used this but it gives me always above mentioned error.

**Comment by billmalarky** [comment]
Paste me a code sample of how you are using it. If you need to anonymize
data that's fine.

**Comment by pravesh19** [comment]
import imageCacheHoc from 'react-native-image-cache-hoc'; 
class allVips extends Component{ 
render(){
      
        var left = (
          <Left style={{flex:1}}>
            <Button onPress={() => this._sideMenuDrawer.open()} transparent>
              <Icon name='ios-menu-outline'/>
            </Button>
          </Left>
        );
       

    return (
   
      <Container>
        <Content>
         <View style={styles.MainContainer}>
            {
            this.state.isFetching && <View style={{ flex: 1}}>  
             <Spinner color='red' overlayColor='rgba(0, 0, 0, 0.5)' visible={this.state.isFetching} textContent={"Loading..."} textStyle={{color: '#2c3e50'}} />
           </View>
           }
          <TextInput 
                style={styles.TextInputStyleClass}
                onChangeText={(text) => this.SearchFilterFunction(text)}
                value={this.state.text}
                underlineColorAndroid='transparent'
                placeholder="Search by Vips First Name and Last Name or by Company"
                  />

        <FlatList
            data={this.state.vipArray}
            removeClippedSubviews={true}
            renderItem={({item}) => <View style={{flex:1, flexDirection: 'column',backgroundColor:'#2E3742', margin:1}}>            
            <View style={{backgroundColor:'#2E3742',alignItems:'center'}}>          
           {/* {  
              item.profile_image == ""?<Image style={styles.ImageComponentStyle} source = {require('../images/default.png')}/>:<Image style={styles.ImageComponentStyle} source = {{ uri: item.profile_image }} />
           }  */}
            {
              item.profile_image == ""?<CacheableImage style={styles.ImageComponentStyle} source = {require('../images/default.png')}/>: <CacheableImage style={styles.ImageComponentStyle} source={{uri:item.profile_image}} permanent={false} placeholder={defaultPlaceholderObject} />
              }


              </View>
            <Text onPress={this.GetGridViewItem.bind(this, item)} style={styles.nameTextStyle} numberOfLines={1} >{item.firstname+' '+item.lastname}</Text>      
            <Text onPress={this.checkstatus.bind(this,item)} style={item.checkin_status==1? styles.ItemTextStyle2:styles.ItemTextStyle} numberOfLines={1} >{item.checkin_status == 1?'Welcomed':'To be Welcomed'}</Text>
            </View> 
            }
            numColumns = { 2 }
            key = {'TWO COLUMN'}
            keyExtractor={(item, index) => index}/>
          </View>
        </Content>
      </Container>

      );
    }
}

export const CacheableImage = imageCacheHoc(Image, {
  validProtocols: ['http','https']
});

export const defaultPlaceholderObject = {
  component: ActivityIndicator,
  props: {
    style: { width:100,
      height:100,
      backgroundColor: '#dc143c'}
  }
};
export default (allVips);

**Comment by billmalarky** [comment]
Ok, and as a sanity check, you have tried this code with https images and confirmed that it works? Also, have you tried this with http images associated with a well known public image host to confirm it isn't an image server problem?

**Comment by pravesh19** [comment]
It is not server issue before I used only HTTP URL with <Image> its working fine. But when I implemented react-native-image-cache-hoc library then I am getting an error. And its also working fine with https.

**Comment by billmalarky** [comment]
What is the http url you are using?

This is the line your url is failing: https://github.com/billmalarky/react-native-image-cache-hoc/blob/9b7f0242905e62414733a81efaa97952804bd03a/lib/imageCacheHoc.js#L132

The next thing I would test is installing validator in your workspace and testing your url like:

validator.isURL(yourUrl);

**Comment by pravesh19** [comment]
Hi,
I got URL issues some URLs open directly in the browser but some asking to save dialog before opening it. I used the validator.isURL() checking.

**Comment by billmalarky** [comment]
It appears your image server has some configuration problems.

You can verify the bug is not in react-native-image-cache-hoc by testing
with a public image. Just grab one from the internet like the stack
overflow logo or something. Just make sure it's http.

**Comment by pravesh19** [comment]
Its working now in both platforms.

**Comment by nlabofa** [comment]
> Its working now on both platforms.

How did you fix this?

**Comment by mike1023** [comment]
> Its working now on both platforms.

How did you fix this?

**Comment by mike1023** [comment]
@pravesh19 how did you fix this? i have same problem.

**Comment by pravesh19** [comment]
hi ,
import imageCacheHoc from 'react-native-image-cache-hoc';
in render set image
{
item.profile_image == ""?<CacheableImage style={styles.ImageComponentStyle}
source = {require('../images/default.png')}/>: <CacheableImage style={styles
.ImageComponentStyle} source={{uri:item.profile_image}} permanent={false}
placeholder={defaultPlaceholderObject} />
}
make sure in plist file  <key>NSAppTransportSecurity</key>  Allow Arbitrary
Loadsshould be yes.
export const CacheableImage = imageCacheHoc(Image, {
validProtocols: ['http','https']
});
