### ISSUE TITLE
Feature Request: Implement PureComponent

### ISSUE THREAD

**Issue by khrizt** [billmalarky/react-native-image-cache-hoc#7]
Could be a great improvement for using image cache hoc inside FlatLists or SectionLists

**Comment by billmalarky** [comment]
https://reactjs.org/docs/react-api.html#reactpurecomponent

Since our render function doesn't make any external calls with side effects there should be no reason we can't implement the HOC as a pure component.

I'll make an update hopefully today or tomorrow.

**Comment by khrizt** [comment]
Nice!!

**Comment by billmalarky** [comment]
More information on PureComponents: https://60devs.com/pure-component-in-react.html

I've implemented and tested this and it looks good. Excellent suggestion.

https://github.com/billmalarky/react-native-image-cache-hoc/commit/71de38449ed116ab11a7f493f32f0930e8941dad

Deployed as version 1.4.0.

**Comment by khrizt** [comment]
Great, thanks a lot!!
